const iconNames = {
  social_media_icons: [
    "facebook",
    "twitter",
    "instagram",
    "linkedin",
    "snapchat",
    "youtube",
    "pinterest",
    "whatsapp",
    "reddit",
    "tumblr",
    "skype",
    "telegram",
    "wechat",
    "vimeo",
  ],
  transportation: [
    "car",
    "bus",
    "bicycle",
    "motorcycle",
    "plane",
    "ship",
    "subway",
    "taxi",
    "train",
    "truck",
    "ambulance",
    "fire-extinguisher",
    "rocket",
    "space-shuttle",
    "wheelchair",
  ],
  weather: [
    "cloud",
    "umbrella",
    "bolt",
    "snowflake-o",
    "sun-o",
    "moon-o",
    "thermometer",
    "thermometer-empty",
    "thermometer-full",
    "thermometer-half",
    "thermometer-quarter",
    "thermometer-three-quarters",
  ],
};

export default iconNames;